tasks:
  # - name: aws-cli
  #   env:
  #     AWS_CLI_AUTO_PROMPT: on-partial
  #   before: |
  #     source ./bin/install_aws_cli

  # - name: azure-agent
  #   before: | 
  #     source ./bin/install_azure_agent
  
  - name: Start Docker Compose
    before: |
      docker-compose build --pull
      docker-compose up -d
# vscode:
#   extensions:
#     - amazonwebservices.aws-toolkit-vscode