version: '3'
services:
  agent:
    build: .
    environment: 
      - TOKEN=${TOKEN}
      - REPO=${REPO}
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - logvolume01:/var/log
    restart: always
volumes:
  logvolume01: {}
